<?php

declare(strict_types=1);

namespace Mojeed\BuckhillCurrencyConverter\Tests;

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Mojeed\BuckhillCurrencyConverter\Providers\BuckhillCurrencyConverterServiceProvider;
use Orchestra\Testbench\TestCase as BaseTest;

class TestCase extends BaseTest
{
    use DatabaseMigrations;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Define environment setup.
     *
     * @param Application $app
     * @return void
     */
    protected function getEnvironmentSetUp($app): void
    {
        // Setup default database to use sqlite :memory:
        $app['config']->set('database.default', 'exchange_rates');
        $app['config']->set('database.connections.exchange_rates', [
            'driver' => 'sqlite',
            'database' => ':memory:',
            'prefix' => '',
        ]);
    }

    /**
     * add the package provider
     *
     * @param $app
     * @return array
     */
    protected function getPackageProviders($app): array
    {
        return [BuckhillCurrencyConverterServiceProvider::class];
    }
}
