<?php

namespace Mojeed\BuckhillCurrencyConverter\Tests;

use Orchestra\Testbench\TestCase as BaseTest;

class TestCase extends BaseTest
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
